server:
  port: 8091


jwt:
  secret: "493358340235739058340598340598340598340598340598"

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        #USUARIOS
        - id: service-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/usuarios/**, /api/v1/auth/**

        # CLIENTES
        - id: cliente-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/clientes/**, /api/v1/direcciones/**
          filters:
            - AuthenticationFilter

        # CATÁLOGO
        - id: catalogo-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/productos/**, /api/v1/categoria/**

        # DISEÑOS
        - id: diseno-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/disenos/**

        # PEDIDOS
        - id: pedidos-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/pedidos/**, /api/v1/detalles/** 
          filters:
            - AuthenticationFilter

        # RESEÑAS
        - id: resenas-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/resenas/**

        # LISTA DE DESEOS
        - id: lista-deseos-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/listadeseos/**
          filters:
            - AuthenticationFilter

        # NOTIFICACIONES
        - id: notificaciones-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - AuthenticationFilter 
        
        # DESPACHO
        - id: despacho-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/despachos/**
        
        #PAGO
        - id: service-pago
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/pagos/**, /api/v1/transacciones/** 

        # DOCUMENTACIÓN USUARIOS
        - id: usuarios-docs
          uri: http://localhost:8081
          predicates:
            - Path=/docs-usuarios/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN CLIENTES
        - id: cliente-docs
          uri: http://localhost:8082
          predicates:
            - Path=/docs-clientes/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN CATÁLOGO
        - id: catalogo-docs
          uri: http://localhost:8083
          predicates:
            - Path=/docs-catalogo/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN DISEÑOS
        - id: diseno-docs
          uri: http://localhost:8084
          predicates:
            - Path=/docs-disenos/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN PEDIDOS
        - id: pedidos-docs
          uri: http://localhost:8085
          predicates:
            - Path=/docs-pedidos/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN RESEÑAS
        - id: resenas-docs
          uri: http://localhost:8086
          predicates:
            - Path=/docs-resenas/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN LISTA DE DESEOS
        - id: lista-deseos-docs
          uri: http://localhost:8087
          predicates:
            - Path=/docs-listadeseos/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN NOTIFICACIONES
        - id: notificaciones-docs
          uri: http://localhost:8088
          predicates:
            - Path=/docs-notificaciones/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # DOCUMENTACIÓN DESPACHO
        - id: despacho-docs
          uri: http://localhost:8089
          predicates:
            - Path=/docs-despacho/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        
        # DOCUMENTACIÓN PAGO
        - id: pago-docs
          uri: http://localhost:8090
          predicates:
            - Path=/docs-pago/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Usuarios API
        url: /docs-usuarios/v3/api-docs
      - name: Clientes API
        url: /docs-clientes/v3/api-docs

      - name: Catálogo API
        url: /docs-catalogo/v3/api-docs

      - name: Diseños API
        url: /docs-disenos/v3/api-docs

      - name: Pedidos API
        url: /docs-pedidos/v3/api-docs

      - name: Reseñas API
        url: /docs-resenas/v3/api-docs

      - name: Lista de Deseos API
        url: /docs-listadeseos/v3/api-docs

      - name: Notificaciones API
        url: /docs-notificaciones/v3/api-docs
      
      - name: Despacho API
        url: /docs-despacho/v3/api-docs

      - name: Pago API
        url: /docs-pago/v3/api-docs

logging:
    level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.http.server.reactive: DEBUG